#!/bin/bash

xgettext --language=Python --keyword=_ --output=updatemanager.pot usr/lib/solydxk/updatemanager/updatemanager.py usr/lib/solydxk/updatemanager/checkAPT.py usr/lib/solydxk/updatemanager/changelogRetriever.py usr/lib/solydxk/updatemanager/threadClasses.py usr/lib/solydxk/updatemanager/treeview.py
