#!/bin/bash

function preseed {
  if [ ! -z "$1" ]; then
    echo "$1" | debconf-set-selections
  fi
}

preseed 'libc6 glibc/upgrade boolean true'
#preseed 'libc6:amd64 glibc/upgrade boolean true'
#preseed 'libc6:i386 glibc/upgrade boolean true'