#!/bin/sh

# Kill the current update manager process
killall -I -q updatemanager 2>/dev/null

# Save the latest UP version from the old hist file
UPHIST=/usr/lib/solydxk/updatemanager/up.hist
UMHIST=/usr/lib/solydxk/updatemanager/updatemanager.hist
if [ -f $UPHIST ] && [ ! -e $UMHIST ]; then
  UPVER=$(cat $UPHIST | tail -n 1)
  echo "up=$UPVER" >> $UMHIST
  rm -f $UPHIST
fi
